[filter]
timeout = 3                     # proxies timeout in seconds.
scrape_timeout = 10             # timeout for scraping proxies.
http = true                     # scrape + check http proxies.
socks4 = true                   # scrape + check socks4 proxies.
socks5 = true                   # scrape + check socks5 proxies.

[options]
scrape = true                    # scrape proxies from url.csv.
threads = 800                    # maximum checking threads.
scrape_threads = 100             # maximum threads while scraping proxies.
save_transparent = false         # transparent proxies don't hide your real IP.
show_dead_proxies = false        # print dead proxies in console, disable it can give better performances
remove_url_on_error = false       # remove url from csv when program got error while scrapping page (timeout etc..)
check_scraped_proxies = true     # check freshly scrapped proxies.

[dev]
debug = true                     # show errors